const category = [
  {
    id: 1,
    tourType: "International",
    image: "./images/us.jpg",
    imgtext: "August 24th,2022",
    heading: "USA",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " USA",
    duration: 3,
    price: "From ₹15000",
  },
  {
    id: 2,
    tourType: "International",
    image: "./images/london.jpg",
    imgtext: "September 15th,2023",
    heading: "London",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " London",
    duration: 5,
    price: "From ₹18000",
  },
  {
    id: 3,
    tourType: "International",
    image: "./images/hk.jpg",
    imgtext: "May 24th,2022",
    heading: "Explore Hong Kong",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Hongkong",
    duration: 5,
    price: "From ₹20000",
  },
  {
    id: 4,
    tourType: "Religious",
    image: "./images/madurai.jpg",
    imgtext: "Jun 24th,2022",
    heading: "Meenakshi Temple",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Madurai",
    duration: 11,
    price: "From ₹3000",
  },
  {
    id: 5,
    tourType: "Religious",
    image: "./images/mahabalipuram.jpg",
    imgtext: "July 24th,2022",
    heading: "Mahabalipuram",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Chennai",
    duration: 3,
    price: "From ₹5000",
  },
  {
    id: 6,
    tourType: "Religious",
    image: "./images/kasi.jpg",
    imgtext: "August 24th,2022",
    heading: "Kashi",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Kashi",
    duration: 3,
    price: "From ₹15000",
  },
  {
    id: 7,
    tourType: "HillStation",
    image: "./images/jammukk.jpg",
    imgtext: "August 24th,2022",
    heading: "Jummu and Kashmir",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Kashmir",
    duration: 5,
    price: "From ₹15000",
  },
  {
    id: 8,
    tourType: "HillStation",
    image: "./images/ooty.jpg",
    imgtext: "August 24th,2022",
    heading: "Ooty",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Ooty",
    duration: 11,
    price: "From ₹10000",
  },
  {
    id: 9,
    tourType: "HillStation",
    image: "./images/himach.jpg",
    imgtext: "August 24th,2022",
    heading: "Himachal Pradesh",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Himachal",
    duration: 10,
    price: "From ₹17000",
  },
  {
    id: 10,
    tourType: "HillStation",
    image: "./images/kodai.jpg",
    imgtext: "August 24th,2022",
    heading: "Kodaikanal",
    para: "Tours provide simplicity in planning by taking care of the details for you. They organize transportation and provide you with information about the places you're seeing.",
    place: " Kodakanal",
    duration: 10,
    price: "From ₹2000",
  },
];

export default category;
